In [25]:
import pandas as pd

In [26]:
bios=pd.read_csv('./bios.csv')
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
cleaned_bios=bios.copy()

In [28]:
# to remove • from names of athletes
cleaned_bios['name']=bios['Used name'].str.replace("•"," ")

In [29]:

# to seperate "Measurements" column into "Height" and "Weight" columns

cleaned_bios[['Height', 'Weight']] = bios['Measurements'].str.split('/', expand=True)
cleaned_bios['height_in_cm']=pd.to_numeric(cleaned_bios['Height'].str.strip(' cm'),errors='coerce')
cleaned_bios['weight_in_kg']=pd.to_numeric(cleaned_bios['Weight'].str.strip(' kg'),errors='coerce')

In [30]:

# to extract date of birth and death 

date_pattern=r'(\d+ \w+ \d{4}|\d{4})';
cleaned_bios['born_date']=cleaned_bios['Born'].str.extract(date_pattern)
cleaned_bios['born_year']=cleaned_bios['Born'].str.extract(r'(\d{4})')

cleaned_bios['born_date']=pd.to_datetime(cleaned_bios['born_date'],format='mixed',errors='coerce')
cleaned_bios['born_year']=pd.to_numeric(cleaned_bios['born_year'])

cleaned_bios['died_date']=cleaned_bios['Died'].str.extract(date_pattern)
cleaned_bios['died_date']=pd.to_datetime(cleaned_bios['died_date'],format='mixed',errors='coerce')

In [ ]:
# to extract born region, city and country from "Born" column
location_pattern = r'in ([\w\s-]+), ([\w\s-]+) \((\w+)\)'
cleaned_bios[['born_region','born_city','born_country']]=cleaned_bios['Born'].str.extract(location_pattern,expand=True)

In [ ]:
# to remove unnecessary columns
needed_columns=['athlete_id','name','born_date','born_city','born_region','born_country','NOC','height_in_cm','weight_in_kg','died_date']
cleaned_data=cleaned_bios[needed_columns]

In [34]:
cleaned_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_in_cm,weight_in_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Gironde,Bordeaux,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Yvelines,Meulan,FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,1898-08-13,Pyrénées-Atlantiques,Biarritz,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris,Paris VIIIe,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,England,Wandsworth,GBR,France,NaN,NaN,1930-07-25

In [36]:
cleaned_data.to_csv('cleaned_bios.csv', index=False)